# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the remainder of the application
COPY . .

# Build the application
RUN npm run build

# Expose port if necessary (optional)
# EXPOSE 3000

CMD [ "node", "dist/index.js" ]
